### ISSUE TITLE
笔趣阁能全站下载吗

### ISSUE THREAD

**Issue by tomas-soua** [BowenZ217/novel-downloader#18]
**Is your feature request related to a problem? Please describe. / 此功能请求是否与某个问题相关？**
A clear and concise description of what the problem is.
请描述你遇到的问题或限制（如有）

**Describe the feature you'd like / 描述你希望添加的功能**
你希望添加什么功能？它应该怎么工作？

**Describe alternatives you've considered / 你考虑过的替代方案**
是否有其他实现方式？

**Additional context / 补充信息**
Add any other context or CLI example here.
比如使用示例、参数设计、配置项，返回什么结果等。

**Comment by BowenZ217** [comment]
应该是大致没问题了

步骤:

1. 打开 [笔趣阁](http://www.b520.cc)
2. 找到想下载的小说页面, 并复制小说的 ID

   * 例如链接 `http://www.b520.cc/8_8187/`, ID 就是 `8_8187`

---

### 安装与配置

更新

```bash
pip install --upgrade novel-downloader

novel-cli settings init
```

然后编辑当前目录下的 `settings.toml` 文件, 配置 `[sites.biquge]` 区块, 例如:

```toml
[sites.biquge]
book_ids = [
  "8_8187",
  "54_321",
  # 去掉原本的占位符
]
mode = "session"  # 可选: session (稳定) 或 async (高并发, 但还在测试)
```

也可以看情况修改其它配置例如

```toml
# 全局通用设置
[general]
request_interval = 2.0
```

---

### 开始下载

```bash
# (可选) 使用 async 的话需要更新规则文件
# novel-cli settings update-rules ./rules.toml

novel-cli download --site biquge
```
