### ISSUE TITLE
[bug] Encrypted content not extracted correctly — shows "inacessive"

### ISSUE THREAD

**Issue by TirelessHunter1** [BowenZ217/novel-downloader#42]
**Describe the bug / 描述问题**
When using the `novel-cli download` command with both encrypted and plain versions, the tool successfully fetches both. However, the encrypted version returns an “inaccessible” page instead of the actual content, even though the plain version seems to work. This suggests that the encrypted version is not being parsed or retrieved correctly.
PS. I would like to point out that version 1.4.0 worked correctly and featured automatic scrolling while making new requests for each page.

**To Reproduce / 重现步骤**

1. Run the following command:

   ```
   novel-cli download --start 8049321 --end 1234 1233456
   ```
2. Wait for both encrypted and plain versions to be fetched.
3. Open the downloaded file from the encrypted version.
4. Observe that it shows a page with the message "inacessive" instead of the actual content.

**Expected behavior / 预期行为**
Both encrypted and plain versions should return the actual HTML content of the novel. The encrypted version should **not** result in an "inaccessible" page.

**Actual behavior / 实际行为**
The encrypted version results in a page showing only "inacessive", while the plain version contains the expected text.

**Environment / 运行环境信息**

* OS: Windows 10
* Python version: 3.11.0
* novel\_downloader version: 1.4.2

**Additional context / 补充信息**

* I focused primarily on the encrypted version, but I believe the issue may also affect the plain version under certain conditions.
* Adjusting the request settings (timeout, retries, interval, etc.) had no effect.
* My current `[requests]` config includes:

  ```toml
  retry_times = 3
  backoff_factor = 5.0
  timeout = 30.0
  max_connections = 10
  max_rps = 1.0
  browser_type = "chromium"
  verify_ssl = true
  ```
* `[general]` settings include:

  ```toml
  request_interval = 5.0
  headless = false
  skip_existing = true
  storage_backend = "sqlite"
  download_workers = 2
  parser_workers = 2
  ```

![Image](https://github.com/user-attachments/assets/a2c75a9a-67ef-4e38-a1e6-34757af78275)

**Comment by BowenZ217** [comment]
For current version of `novel-cli`, it doesn't rely on front-end JS rendering but instead extracts the server-rendered JSON blob embedded in the HTML -- specifically from the `<script id="vite-plugin-ssr_pageContext">` block.

So in cases where you see that "inaccessible" screen, it's not necessarily a failure. The parser is usually working correctly behind the scenes. I haven’t fixing this (still looking into what exactly causes it) because the content is still successfully extracted.

It's possible that some of Chrome-related settings are causing the visual page load to look broken, but the actual parsing is unaffected.

You can verify this by either:

* Exporting the novel using:

  ```bash
  novel-cli export --format txt 8049321
  ```

* Or by changing `[general]`'s `storage_backend` to `"json"` and then checking:

  ```
  {raw_data}/qidian/{book_id}/{chapters | encrypted_chapters}/{chapter_id}.json
  ```

  You should find the correct chapter content inside those JSON files.

Are you specifically looking to extract or analyze something from the raw HTML output?

**Comment by BowenZ217** [comment]
Just to check -- during the download process with `novel-cli`, did you have font decryption enabled in your `./settings.toml` file?

By default, I have it turned **off**, so if it's not explicitly enabled, the encrypted chapters may not get decoded properly. The relevant config section is:

```toml
[general.font_ocr]
decode_font = true      # Whether to attempt local deobfuscation of the font
use_freq = false
ocr_version = "v2.0"    # "v1.0" or "v2.0"
use_ocr = true          # Whether to use OCR
use_vec = true          # Whether to use vector features
save_font_debug = false
batch_size = 64
gpu_mem = 2000
ocr_weight = 0.5
vec_weight = 0.5
```

You might want to make sure `decode_font = true` and `use_ocr = true` if you're trying to extract readable content from the obfuscated HTML.
